name = "transaction_commit"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TwoPhase", "PaxosCommit", "«2PCwithBTM»"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "TCommit"

[[lean_lib]]
name = "TwoPhase"

[[lean_lib]]
name = "PaxosCommit"

[[lean_lib]]
name = "«2PCwithBTM»"
